### PR TITLE
added centered thumbnail to readme file

### PR DESCRIPTION
**Pull request by RivaD2**
**Worked with partner Darius Lee Pasilaban**
- [x] Added `banner-thumbnail` from Figma mock up  to `Readme.md` (took banner section for use)
     - [x] Removed html markup from page
    - [x] Worked on branch thumbnail-to-readme

### CODE REVIEW

**Comment by kafiln** [comment]
Thank you for contributing.
Could you please just change the image that you used. I don't think that my face can be used as a banner 🤣.

**Review by kafiln — CHANGES_REQUESTED** [review]
Jumbotron
Maybe use this image 👍🏾 
Thank you

**Comment by RivaD2** [comment]
We updated the image for you and used the one from Figma :) We thought that it was wrong to use your headshot as a banner but hey, now I think we might have it right lol

**Comment by kafiln** [comment]
Thanks and congrats for your first contribution.
Hope it won't be the last.
Cheers

**Comment by RivaD2** [comment]
Thank you so much! It was scary but we made it through. It was a pleasure working with you. Cheers!

**Pull request merged**
